version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: nova-lite-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nova_lite
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: nova-lite-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nova-lite-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
